// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace FrameWorkApp
{
	public partial class MenuScreenTiles : UIViewController
	{
		public MenuScreenTiles (IntPtr handle) : base (handle)
		{
		}

		partial void menuToHome (NSObject sender)
		{
			DismissViewController(true,null);
		}
	}
}
