// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.Foundation;

namespace FrameWorkApp
{
	public partial class TripSummaryScreen : UIViewController
	{
		public TripSummaryScreen (IntPtr handle) : base (handle)
		{

		}

		partial void toHome (NSObject sender)
		{
			StopScreenn.coordList.Clear();
			DismissModalViewControllerAnimated(true);
		}

	}
}
